import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

/**
 * Created by natalia on 12/25/14.
 */
public class MainWindow {
    private JPanel MainPanel;
    private JList list1;
    private JScrollPane listPanel;
    private JButton upload;
    private JButton przetwórzButton;
    private JRadioButton radioButton1;
    private JRadioButton radioButton2;
    private DefaultListModel fileListModel;

    public MainWindow() {
        upload.addActionListener(new clickUploadListener());
        fileListModel = new DefaultListModel();
        list1.setModel(fileListModel);
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(radioButton1);
        buttonGroup.add(radioButton2);
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("MainWindow");
        // frame.setSize(600, 480);
        frame.setContentPane(new MainWindow().MainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new FormLayout("fill:293px:noGrow,left:4dlu:noGrow,fill:159px:noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,top:227dlu:noGrow,center:64px:noGrow"));
        listPanel = new JScrollPane();
        CellConstraints cc = new CellConstraints();
        MainPanel.add(listPanel, new CellConstraints(1, 3, 1, 1, CellConstraints.DEFAULT, CellConstraints.FILL, new Insets(5, 5, 5, 5)));
        list1 = new JList();
        list1.putClientProperty("List.isFileList", Boolean.TRUE);
        listPanel.setViewportView(list1);
        upload = new JButton();
        upload.setText("Wgraj zdjęcia");
        MainPanel.add(upload, cc.xy(1, 1));
        przetwórzButton = new JButton();
        przetwórzButton.setText("Button");
        MainPanel.add(przetwórzButton, cc.xy(3, 4));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow", "center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        MainPanel.add(panel1, cc.xy(3, 3));
        radioButton1 = new JRadioButton();
        radioButton1.setText("RadioButton");
        panel1.add(radioButton1, cc.xy(1, 3));
        radioButton2 = new JRadioButton();
        radioButton2.setText("RadioButton");
        panel1.add(radioButton2, cc.xy(1, 5));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

    public class clickUploadListener implements ActionListener {
        public void actionPerformed(ActionEvent e) {
            JFileChooser chooser = new JFileChooser();
            FileFilter imageFilter = new FileNameExtensionFilter(
                    "Image files", ImageIO.getReaderFileSuffixes());
            chooser.setFileFilter(imageFilter);

            chooser.setMultiSelectionEnabled(true);
            chooser.showOpenDialog(null);
            File[] files = chooser.getSelectedFiles();
            for (File file : files) fileListModel.addElement(file);
        }
    }
}
